on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: ""
        source_branch: ""
        destination_repo: ""
        destination_branch: ""
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
